
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY ["OkumaUygulamasi.API/OkumaUygulamasi.API.csproj", "OkumaUygulamasi.API/"]
RUN dotnet restore "OkumaUygulamasi.API/OkumaUygulamasi.API.csproj"

COPY . .
WORKDIR "/src/OkumaUygulamasi.API"
RUN dotnet publish "OkumaUygulamasi.API.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "OkumaUygulamasi.API.dll"]